---
title: "Prior Analytics"
include-in-header: files/logo-regular.html
---

Welcome to **Prior Analytics**! My name is Michael Flynn and I offer independent statistical and data analysis consulting services. 

# What do I offer?

Whether it’s private businesses, non-profits, or government agencies, people often find themselves trying to solve complex problems. Increasingly these challenges involve wrangling large amounts of data as businesses try to better understand these problems and identify possible solutions. 

My specialization involves the use of statistical and computational methods to help you at whatever stage of this process your organization may be in. Whether its analyzing large amounts of data, or helping you to figure out how to ask the right questions, I can assist you. Specifically, I offer the following types of services, including but not limited to:

- Data analysis
- Designing surveys
- Written reports
- Statistical analysis
- Public lectures/presentations
- Private/organizational briefings


# My approach

I have over a decade of training and experience in the social sciences, blending advanced statistical techniques with a consistent focus on the substantive issues that matter to people. With these skills I can help you and your business adopt a data-driven approach to identify solutions to complex and challenging problems. 

While others may have similar technical abilities, by background in political science means that whatever the statistical and computational methods I use, I will always maintain a focus on making sure you can easily identify the key takeaways and solutions that your business cares about. 

Beyond blending advanced statistical methods with a clear and concise presentation, I can also offer you these tools and insight for less than major consulting firms or an in-house data science team would cost. Technology should help us to break down barriers to comprehension, allowing us to better understand the issues we care about—not create more confusion.

No matter your needs, my approach always prioritizes developing a better understanding of the underlying patterns of human behavior. To that end I will provide you with clear and concise analyses that meet your needs.


## Contact 

If you'd like to talk don't hesitate to email me. I will respond to you as soon as possible. I look forward to helping you with your company's projects!

Email me at [michaelflynn@prioranalytics.net](mailto:michaelflynn@prioranalytics.net)
